In [1]:
import csv

# booksummaries.txt is tab-separated despite the .txt extension
with open("booksummaries.txt", "r", encoding="utf-8") as book_file:
    book_lines = book_file.readlines()

with open("book.csv", "w", newline="", encoding="utf-8") as csv_book_file:
    writer = csv.writer(csv_book_file)
    writer.writerow(['WikipediaID', 'FreebaseID', 'Title', 'Author', 'Publication Date', 'Genres', 'Summary'])
    for line in book_lines:
        parts = line.strip().split('\t')
        writer.writerow(parts)

print("CSV file 'book.csv' created successfully.")

CSV file 'book.csv' created successfully.

In [2]:
import pandas as pd

file_path = "book.csv"
df_book = pd.read_csv(file_path)

df_book

,WikipediaID,FreebaseID,Title,Author,Publication Date,Genres,Summary
0,620,/m/0hhy,Animal Farm,George Orwell,1945-08-17,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca..."
1,843,/m/0k36,A Clockwork Orange,Anthony Burgess,1962,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan..."
2,986,/m/0ldx,The Plague,Albert Camus,1947,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...
3,1756,/m/0sww,An Enquiry Concerning Human Understanding,David Hume,NaN,NaN,The argument of the Enquiry proceeds by a ser...
4,2080,/m/0wkt,A Fire Upon the Deep,Vernor Vinge,NaN,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...
...,...,...,...,...,...,...,...
16554,36934824,/m/0m0p0hr,Under Wildwood,Colin Meloy,2012-09-25,NaN,"Prue McKeel, having rescued her brother from ..."
16555,37054020,/m/04f1nbs,Transfer of Power,Vince Flynn,2000-06-01,"{""/m/01jfsb"": ""Thriller"", ""/m/02xlf"": ""Fiction""}",The reader first meets Rapp while he is doing...
16556,37122323,/m/0n5236t,Decoded,Jay-Z,2010-11-16,"{""/m/0xdf"": ""Autobiography""}",The book follows very rough chronological ord...
16557,37132319,/m/0n4bqb1,America Again: Re-becoming The Greatness We Ne...,Stephen Colbert,2012-10-02,NaN,Colbert addresses topics including Wall Stree...
16558,37159503,/m/073nkd,Poor Folk,Fyodor Dostoyevsky,1846,"{""/m/02ql9"": ""Epistolary novel"", ""/m/014dfn"": ...",Makar Devushkin and Varvara Dobroselova are s...

In [3]:
df = df_book.drop(columns=['WikipediaID', 'FreebaseID', 'Author', 'Publication Date', 'Genres'], axis=1)

df

,Title,Summary
0,Animal Farm,"Old Major, the old boar on the Manor Farm, ca..."
1,A Clockwork Orange,"Alex, a teenager living in near-future Englan..."
2,The Plague,The text of The Plague is divided into five p...
3,An Enquiry Concerning Human Understanding,The argument of the Enquiry proceeds by a ser...
4,A Fire Upon the Deep,The novel posits that space around the Milky ...
...,...,...
16554,Under Wildwood,"Prue McKeel, having rescued her brother from ..."
16555,Transfer of Power,The reader first meets Rapp while he is doing...
16556,Decoded,The book follows very rough chronological ord...
16557,America Again: Re-becoming The Greatness We Ne...,Colbert addresses topics including Wall Stree...
16558,Poor Folk,Makar Devushkin and Varvara Dobroselova are s...

In [4]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

In [ ]:
df['Title+Summary'] = df['Title'] + ', ' + df['Summary']

df_book['embeddings2'] = df['Title+Summary'].apply(lambda x: model.encode(x))

df_book

,WikipediaID,FreebaseID,Title,Author,Publication Date,Genres,Summary,embeddings2
0,620,/m/0hhy,Animal Farm,George Orwell,1945-08-17,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca...","[-0.006293754, -0.005122641, 0.025438314, 0.01..."
1,843,/m/0k36,A Clockwork Orange,Anthony Burgess,1962,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan...","[-0.029204553, -0.016188992, -0.01736793, 0.03..."
2,986,/m/0ldx,The Plague,Albert Camus,1947,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...,"[0.059276205, 0.0641227, 0.024995258, -0.03684..."
3,1756,/m/0sww,An Enquiry Concerning Human Understanding,David Hume,NaN,NaN,The argument of the Enquiry proceeds by a ser...,"[-0.001947841, -0.026068553, -0.033532467, -0...."
4,2080,/m/0wkt,A Fire Upon the Deep,Vernor Vinge,NaN,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...,"[-0.06273436, -0.07693547, -0.0336505, 0.05363..."
...,...,...,...,...,...,...,...,...
16554,36934824,/m/0m0p0hr,Under Wildwood,Colin Meloy,2012-09-25,NaN,"Prue McKeel, having rescued her brother from ...","[-0.0034177466, -0.029791065, -0.02162453, 0.0..."
16555,37054020,/m/04f1nbs,Transfer of Power,Vince Flynn,2000-06-01,"{""/m/01jfsb"": ""Thriller"", ""/m/02xlf"": ""Fiction""}",The reader first meets Rapp while he is doing...,"[-0.08045152, 0.03969828, 0.019140668, 0.03675..."
16556,37122323,/m/0n5236t,Decoded,Jay-Z,2010-11-16,"{""/m/0xdf"": ""Autobiography""}",The book follows very rough chronological ord...,"[-0.02317341, -0.01630708, 0.013071433, 0.0167..."
16557,37132319,/m/0n4bqb1,America Again: Re-becoming The Greatness We Ne...,Stephen Colbert,2012-10-02,NaN,Colbert addresses topics including Wall Stree...,"[0.06035095, -0.002714156, 0.007763445, -0.009..."
16558,37159503,/m/073nkd,Poor Folk,Fyodor Dostoyevsky,1846,"{""/m/02ql9"": ""Epistolary novel"", ""/m/014dfn"": ...",Makar Devushkin and Varvara Dobroselova are s...,"[0.023207882, 0.021607963, -0.042096205, 0.023..."

In [6]:
df_book.to_csv("book.csv", index=False)

In [7]:
query = "War"

query_embedding = model.encode(query)

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def recherche_book(query_embedding, df, top_k=5):

    # Calculate cosine similarity between the query embedding and the embeddings in the DataFrame
    similarities = cosine_similarity([query_embedding], df['embeddings2'].tolist())[0]
    
    # Get the indices of the top_k most similar items
    top_indices = np.argsort(similarities)[-top_k:][::-1]
    
    # Return the top_k most similar items
    return df.iloc[top_indices, 3]

print(recherche_book(query_embedding, df_book, top_k=5))

10494         Simon Green
10589    Trevor Baxendale
6992         Ralph Peters
5501         Lance Parkin
6985        Robert Greene
Name: Author, dtype: object

In [11]:
import faiss

vectors = df_book['embeddings2'].tolist()
vectors = np.array(vectors).astype('float32')

index = faiss.IndexFlatIP(384)  # 384 is the dimension of the embeddings for 'all-MiniLM-L6-v2'
index.add(vectors)

In [12]:
query = "War"

query_embedding = model.encode(query)
query_embedding = np.array(query_embedding).astype('float32')

In [13]:
D, I = index.search(np.expand_dims(query_embedding, axis=0), 5)


top_books = df.iloc[I[0]]         # I[0] contains the indices of the top 5 matches
top_books[['Title', 'Summary']]

,Title,Summary
10494,Deathstalker War,- --&#62; &#60;!-
10589,War of the Robots,"On a distant world populated by robots, war h..."
6992,The War in 2020,The War in 2020 takes place in a future dysto...
5501,Just War,The Doctor and his companions land in German-...
6985,The 33 Strategies of War,The 33 Strategies of War contains successful ...

In [14]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer

# Load data
csv_path = "book.csv"
df = pd.read_csv(csv_path)
df = df.drop(columns=['WikipediaID', 'FreebaseID', 'Author', 'Publication Date', 'Genres'], axis=1)

# Prepare texts for embedding
texts = (df['Title'] + ', ' + df['Summary']).tolist()

# Load model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Compute embeddings in batch
embeddings = model.encode(texts, show_progress_bar=True, batch_size=64)

# Save embeddings as .npy
np.save("book_embeddings.npy", embeddings)
print(f"Saved {embeddings.shape[0]} embeddings to RAG/book_embeddings.npy")

Batches: 100%|██████████| 259/259 [09:09<00:00,  2.12s/it]

Saved 16559 embeddings to RAG/book_embeddings.npy